In [1]:
import gymnasium as gym

In [2]:
import atari_py

In [5]:
print(gym.envs.registry.keys()) # All the environemnts (like atari environment)

dict_keys(['CartPole-v0', 'CartPole-v1', 'MountainCar-v0', 'MountainCarContinuous-v0', 'Pendulum-v1', 'Acrobot-v1', 'phys2d/CartPole-v0', 'phys2d/CartPole-v1', 'phys2d/Pendulum-v0', 'LunarLander-v2', 'LunarLanderContinuous-v2', 'BipedalWalker-v3', 'BipedalWalkerHardcore-v3', 'CarRacing-v2', 'Blackjack-v1', 'FrozenLake-v1', 'FrozenLake8x8-v1', 'CliffWalking-v0', 'Taxi-v3', 'tabular/Blackjack-v0', 'tabular/CliffWalking-v0', 'Reacher-v2', 'Reacher-v4', 'Pusher-v2', 'Pusher-v4', 'InvertedPendulum-v2', 'InvertedPendulum-v4', 'InvertedDoublePendulum-v2', 'InvertedDoublePendulum-v4', 'HalfCheetah-v2', 'HalfCheetah-v3', 'HalfCheetah-v4', 'Hopper-v2', 'Hopper-v3', 'Hopper-v4', 'Swimmer-v2', 'Swimmer-v3', 'Swimmer-v4', 'Walker2d-v2', 'Walker2d-v3', 'Walker2d-v4', 'Ant-v2', 'Ant-v3', 'Ant-v4', 'Humanoid-v2', 'Humanoid-v3', 'Humanoid-v4', 'HumanoidStandup-v2', 'HumanoidStandup-v4', 'GymV26Environment-v0', 'GymV21Environment-v0', 'Adventure-v0', 'AdventureDeterministic-v0', 'AdventureNoFrameskip-v0

In [4]:
env = gym.make("SpaceInvaders-v0",render_mode='human')

/Users/arghasreebanerjee/opt/anaconda3/envs/XAI_week1/lib/python3.10/site-packages/gymnasium/envs/registration.py:513: DeprecationWarning: WARN: The environment SpaceInvaders-v0 is out of date. You should consider upgrading to version `v4`.
  logger.deprecation(
A.L.E: Arcade Learning Environment (version 0.8.1+53f58b7)
[Powered by Stella]


In [5]:
env.reset()

(array([[[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0],
         ...,
         [ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]],
 
        [[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0],
         ...,
         [ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]],
 
        [[ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0],
         ...,
         [ 0,  0,  0],
         [ 0,  0,  0],
         [ 0,  0,  0]],
 
        ...,
 
        [[80, 89, 22],
         [80, 89, 22],
         [80, 89, 22],
         ...,
         [80, 89, 22],
         [80, 89, 22],
         [80, 89, 22]],
 
        [[80, 89, 22],
         [80, 89, 22],
         [80, 89, 22],
         ...,
         [80, 89, 22],
         [80, 89, 22],
         [80, 89, 22]],
 
        [[80, 89, 22],
         [80, 89, 22],
         [80, 89, 22],
         ...,
         [80, 89, 22],
         [80, 89, 22],
         [80, 89, 22]]], dtype=uint8),
 {'lives': 3, 'episode_frame_number': 0, '

In [6]:
env.render()

/Users/arghasreebanerjee/opt/anaconda3/envs/XAI_week1/lib/python3.10/site-packages/gymnasium/utils/passive_env_checker.py:335: UserWarning: WARN: No render fps was declared in the environment (env.metadata['render_fps'] is None or not defined), rendering may occur at inconsistent fps.
  logger.warn(


In [7]:
action = env.action_space.sample() # From available actions sample 1 action

In [8]:
# Now take that action
# If you take that action, you will get a new state (state after taking the action), reward (reward agent got), is_done/terminated (is the objective reached), truncated, info ()
new_state, reward, terminated, truncated, info = env.step(action)

# The new state is the frame/image for the next state; 
# Reward = 0

In [9]:
print(new_state, reward, terminated, truncated, info)

[[[ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]
  ...
  [ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]]

 [[ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]
  ...
  [ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]]

 [[ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]
  ...
  [ 0  0  0]
  [ 0  0  0]
  [ 0  0  0]]

 ...

 [[80 89 22]
  [80 89 22]
  [80 89 22]
  ...
  [80 89 22]
  [80 89 22]
  [80 89 22]]

 [[80 89 22]
  [80 89 22]
  [80 89 22]
  ...
  [80 89 22]
  [80 89 22]
  [80 89 22]]

 [[80 89 22]
  [80 89 22]
  [80 89 22]
  ...
  [80 89 22]
  [80 89 22]
  [80 89 22]]] 0.0 False False {'lives': 3, 'episode_frame_number': 3, 'frame_number': 3}


In [ ]:
is_done=False
while not is_done:
    action = env.action_space.sample()
    new_state, reward, terminated, truncated, info = env.step(action)
    print(info)
    env.render() # This method updates the window based on the new_state

{'lives': 3, 'episode_frame_number': 5, 'frame_number': 5}
{'lives': 3, 'episode_frame_number': 7, 'frame_number': 7}
{'lives': 3, 'episode_frame_number': 11, 'frame_number': 11}
{'lives': 3, 'episode_frame_number': 15, 'frame_number': 15}
{'lives': 3, 'episode_frame_number': 18, 'frame_number': 18}
{'lives': 3, 'episode_frame_number': 22, 'frame_number': 22}
{'lives': 3, 'episode_frame_number': 25, 'frame_number': 25}
{'lives': 3, 'episode_frame_number': 28, 'frame_number': 28}
{'lives': 3, 'episode_frame_number': 32, 'frame_number': 32}
{'lives': 3, 'episode_frame_number': 34, 'frame_number': 34}
{'lives': 3, 'episode_frame_number': 38, 'frame_number': 38}
{'lives': 3, 'episode_frame_number': 40, 'frame_number': 40}
{'lives': 3, 'episode_frame_number': 43, 'frame_number': 43}
{'lives': 3, 'episode_frame_number': 45, 'frame_number': 45}
{'lives': 3, 'episode_frame_number': 47, 'frame_number': 47}
{'lives': 3, 'episode_frame_number': 51, 'frame_number': 51}
{'lives': 3, 'episode_frame_

In [7]:
env.action_space # There are 6 actions that the agent can take: No operation, Fire, Up, Right, Left, Down

Discrete(6)

In [8]:
action = env.action_space.sample()
new_state, reward, terminated, truncated, info = env.step(action)

In [13]:
print(new_state.shape, type(new_state)) # new_state is a rgb image of shape: (210, 160, 3)

(210, 160, 3) <class 'numpy.ndarray'>


In [18]:
env= gym.make('LunarLander-v2', render_mode="rgb_array")
env.reset()
env.render()

array([[[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]

In [10]:
from gym.wrappers.monitoring.video_recorder import VideoRecorder

env = gym.make('CartPole-v0', render_mode="rgb_array")
env.reset()

(array([-0.04814595,  0.02118817, -0.01469867, -0.04369907], dtype=float32),
 {})

In [4]:
env.render()

array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       ...,

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [255, 255, 255]]

In [12]:
is_done= False
while not is_done:
    action = env.action_space.sample()
    new_state, reward, is_done, truncated, info = env.step(action)
    print(new_state) # Array of 4 elements: [cart position, cart velocity, pole angle, pole velocity]
    print(reward) # Reward = 1.0 = constant for each action, if the episode has terminated, reward = 0
    env.render()

[-0.10439104  0.1719951   0.22350053  0.656478  ]
0.0


In [18]:
n_episode = 100; total_reward_per_episode =0; 
for episode in range(n_episode):
    env.reset()
    is_done = False
    while not is_done:
        action = env.action_space.sample()
        new_state, reward, is_done, truncated, info = env.step(action)
        env.render()
        total_reward_per_episode += reward
avg_rewards = total_reward_per_episode/n_episode

print(f'Average reward per episode: {avg_rewards}')

Average reward per episode: 20.79
